### ISSUE TITLE
strange yaourt behavior

### ISSUE THREAD

**Issue by leongm** [archlinuxfr/yaourt#154] opened 2015-10-03 13:16 UTC
Hi there,

$ yaourt -Ss perl cups  
/usr/lib/yaourt/util.sh : ligne 166 :  7394 Erreur de segmentation  (core dumped)package-query "${PKGQUERY_C_ARG[@]}" "$@"

while

$ yaourt -Ss cups perl
1 aur/perl-net-cups 0.61-1 (3)
    Common Unix Printing System Interface

**Comment by The-Compiler** [comment] 2015-10-03 16:25
See #133, #146, #152 and https://github.com/archlinuxfr/package-query/issues/13 :wink:

It was fixed in https://github.com/archlinuxfr/package-query/pull/14

**Closed** 2015-10-06 08:50 UTC

**Comment by kgleason** [comment] 2016-03-02 14:51
Is it possible that this (or one of the other referenced issues) has regressed?

When I run `yaourt -Syyua --noconfirm` I get a core dump. I also get it when I run without `--noconfirm`

> /usr/lib/yaourt/util.sh: line 166:  2635 Illegal instruction     (core dumped) package-query "${PKGQUERY_C_ARG[@]}" "$@"

Been happening for 2 days now. I can run `sudo pacman -Syyu` with no issue.

**Comment by f2404** [comment] 2016-03-02 15:05
What versions of yaourt and package-query are you using?

**Comment by kgleason** [comment] 2016-03-02 15:25
Well the output of the first command here seems odd

> kirk@kirkdt:~$ yaourt -V
>yaourt 
>homepage: http://archlinux.fr/yaourt-en
>kirk@kirkdt:~$ package-query -v
>package-query 1.8
>kirk@kirkdt:~$ sudo pacman -Q yaourt
>yaourt 1.7-2

**Comment by f2404** [comment] 2016-03-02 15:48
Does the crash happen on running `yaourt -Ss perl cups` as mentioned above?

**Comment by f2404** [comment] 2016-03-02 16:11
@kgleason I cannot reproduce your issue even after having installed yaourt-1.7 and package-query-1.8 - release versions.

**Comment by kgleason** [comment] 2016-03-02 20:23
>$ yaourt -Ss perl cups
>/usr/lib/yaourt/util.sh: line 166: 20484 Illegal instruction     (core dumped) package-query "${PKGQUERY_C_ARG[@]}" "$@"

**Comment by larchunix** [comment] 2016-03-02 20:50
The error message looks weird to me. IIUC, `Illegal instruction` means `SIGILL`.

Did you compile package-query on another machine or with special compilation flags ?

**Comment by kgleason** [comment] 2016-03-02 20:52
@larchunix I didn't even know that package-query was installed, so it was most likely installed by yaourt or pacman as a dependency.

@f2404 I haven't modified the `yaourtrc` file, so as far as I know it is stock.

**Comment by kgleason** [comment] 2016-03-02 20:54
@larchunix There are other issues that have the same error, but they all seem to be somewhat aged.

**Comment by larchunix** [comment] 2016-03-02 20:58
@kgleason Could you run `bash -x yaourt -Ss perl cups` and copy/paste the exact command line used to invoke package-query which raises this error ?

**Comment by kgleason** [comment] 2016-03-02 21:00
I see in the topic of #archlinux on FreeNode that "yaourt is broken. You'll need package-query-git". Trying that now

**Comment by kgleason** [comment] 2016-03-02 21:02
Here you go.

> + pkgquery -s -S -s -A -- perl cups
> + package-query --aur-url https://aur.archlinux.org -s -S -s -A -- perl cups
> /usr/lib/yaourt/util.sh: line 166: 22604 Illegal instruction     (core dumped) package-query "${PKGQUERY_C_ARG[@]}" "$@"
> + ret=132

**Comment by kgleason** [comment] 2016-03-02 21:08
package-query-git seems to have resolved it for now.

**Comment by f2404** [comment] 2016-03-03 08:17
> package-query-git seems to have resolved it for now.
That's indeed strange as the git version currently has almost no changes comparing to the 1.8 release version which you seem to have been using...

**Comment by kgleason** [comment] 2016-03-03 13:27
I was going to try to test on my laptop, which is more or less the same config as this machine, but it seems to be having some hardware issues right now.

**Comment by f2404** [comment] 2016-03-03 13:38
Ok, please keep us posted.

**Comment by f2404** [comment] 2016-03-11 14:01
@kgleason Were you able to test it?
