### ISSUE TITLE
Dependency handling in AUR packages slightly broken

### ISSUE THREAD

**Issue by ido** [archlinuxfr/yaourt#72] opened 2015-01-09 11:33 UTC
Installing two packages in which one is a dependency of the other, e.g. "yaourt -Syua compiz-bcop compiz-core" installs the dependency twice.  So in the example, compiz-core would be installed during the installation process for compiz-bcop, but then yaourt doesn't realize that compiz-core is already installed and builds/installs compiz-core again.

This can be fixed pretty easily by keeping track of packages installed (as dependencies) during the installation process and marking them as already installed (removing them from the list of to-be-installed packages).  The packages I have tried with this are only on AUR, I have not checked if the same problem occurs for ABS packages.

**Comment by tuxce** [comment] 2015-01-13 13:14
Duplicate of issue #55

**Closed by tuxce** 2015-01-13 13:14 UTC
