### ISSUE TITLE
"yaourt rar" not working

### ISSUE THREAD

**Issue by ktamp** [archlinuxfr/yaourt#73] opened 2015-01-12 22:36 UTC
"yaourt rar" does not show "aur/rar" as an option.
Instead 1112 irrelevant options (all from repositories, none from AUR) are displayed, due to "rar" being part of the word "library".
Perhaps the word "library" should be blacklisted?

**Comment by tuxce** [comment] 2015-01-13 12:55
AUR does not provide a way to limit search results and returns an error if search terms return too many results : https://aur.archlinux.org/rpc.php?type=search&arg=rar

**Comment by Markus-N** [comment] 2015-03-10 21:27
Maybe the solution would be to add a --namesonly switch (or similar). I think this would be useful for other cases too.

**Comment by f2404** [comment] 2015-11-03 14:36
Please check the patches above if they resolve the issue.

**Comment by f2404** [comment] 2015-12-09 16:35
I think the issue can be closed.

**Comment by Markus-N** [comment] 2015-12-11 21:27
It depends ...
The symptom is fixed, so "yaourt rar" does not crash any more. But the result list is over 4000 items. This makes finding the desired package really cumbersome.
The cause - listing everything that contains "rar" (even "... library ... ") - is still there. I still think that yaourt needs a switch like --nameonly. AFAIK, some user submitted patch for doing that.
Maybe it would be a good idea to submit a feature request to AUR so the filtering can be done on AUR side instead on yourt side.
Blacklisting "library" is also still worth thinking about.

**Comment by f2404** [comment] 2015-12-12 06:16
@Markus-N Please check the patches referenced above - adding "--nameonly" option was exactly what I did.

**Comment by Markus-N** [comment] 2015-12-12 21:16
Yes, I'v seen the patch, but it's not (yet ?) included in yaourt.
yaourt --nameonly rar
gives an error.

**Comment by f2404** [comment] 2015-12-13 13:18
It's been merged but not released yet.
You can use this option if you install the ```yaourt-git``` package (and ```package-query-git```, respectively).

**Comment by f2404** [comment] 2016-02-04 09:23
The issue can be closed, I suppose.

**Comment by larchunix** [comment] 2016-02-04 10:23
Fixed in git (#159).

**Closed by larchunix** 2016-02-04 10:23 UTC
