### ISSUE TITLE
Add an option to prioritize AUR packages over packages in other repos

### ISSUE THREAD

**Issue by valandil** [archlinuxfr/yaourt#100] opened 2015-04-14 20:29 UTC
I haven't seen this documented in the man page of either yaourt.8 or yaourtrc.5, but it would be nice to have an option that prioritizes packages that are both in the AUR and other repos. For instance, I maintain the `armadillo` package on AUR, but it is also available in the `[archlinuxfr]` repo. My version is (for the moment, of course), more up-to-date than the `[archlinuxfr]` version. However, when running
```bash
yaourt -S armadillo
```
yaourt will install the `[archlinuxfr]` version instead of the more up-to-date version on AUR. Could some priority option be added to the AUR?

**Comment by Skunnyk** [comment] 2015-04-28 18:57
Duplicate of https://github.com/archlinuxfr/yaourt/issues/18

**Closed by Skunnyk** 2015-04-28 18:57 UTC
